# Generated by Django 4.1.5 on 2023-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(db_index=True, max_length=5, null=True),
        ),
    ]
