# Generated by Django 4.1.5 on 2023-02-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='helper',
        ),
    ]
