# Generated by Django 4.1.5 on 2023-03-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_rename_is_admin_user_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='congregation',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
