# Generated by Django 4.1.5 on 2023-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_user_congregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupe',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
