# Generated by Django 4.1.5 on 2023-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_user_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groupe',
            field=models.CharField(db_index=True, max_length=5, null=True),
        ),
    ]
