# Generated by Django 4.1.5 on 2023-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_alter_user_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='action',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
