# Generated by Django 4.1.5 on 2023-03-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_user_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='action',
        ),
        migrations.AddField(
            model_name='user',
            name='duty',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='microphones',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='music',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
