# Generated by Django 4.1.5 on 2023-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_user_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='duty',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='microphones',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='music',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
