# Generated by Django 4.1.5 on 2023-03-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_alter_user_duty_alter_user_microphones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='microphones',
        ),
        migrations.RemoveField(
            model_name='user',
            name='music',
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
