# Generated by Django 4.1.5 on 2023-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0012_remove_user_duty_remove_user_microphones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
