# Generated by Django 4.1.5 on 2023-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0017_alter_user_helper_alter_user_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ministry_event',
            field=models.BooleanField(default=False, verbose_name='Ministry (Leader of ministry meetings)'),
        ),
    ]
