# Generated by Django 4.1.5 on 2023-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0018_alter_user_ministry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='helper',
            field=models.BooleanField(default=False, verbose_name='Helper (lector, service, prayers)'),
        ),
    ]
