# Generated by Django 4.1.5 on 2023-03-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0019_alter_user_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor',
            field=models.BooleanField(default=False, verbose_name='Congregation menegment'),
        ),
    ]
