# Generated by Django 4.1.5 on 2023-04-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0021_user_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stand',
            field=models.BooleanField(default=False, verbose_name='Ministry with Stand'),
        ),
    ]
