# Generated by Django 4.1.5 on 2023-04-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0023_user_lector_alter_user_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scool_leader',
            field=models.BooleanField(default=False),
        ),
    ]
