# Generated by Django 4.1.5 on 2023-04-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0024_user_scool_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scool_leader',
            new_name='school_leader',
        ),
    ]
