# Generated by Django 4.1.5 on 2023-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='films',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='minutes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='publications',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='studies',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
