# Generated by Django 4.1.5 on 2023-03-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='groupr',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
