# Generated by Django 4.1.5 on 2023-02-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_event_films_alter_event_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.TextField(max_length=500),
        ),
    ]
