# Generated by Django 4.1.5 on 2023-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_groupr_calendar_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
