# Generated by Django 4.1.5 on 2023-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_event_result_alter_event_films_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='films',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='publications',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='studies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visits',
            field=models.IntegerField(null=True),
        ),
    ]
