# Generated by Django 4.1.5 on 2023-02-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_hoursresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursresult',
            name='user',
        ),
    ]
