# Generated by Django 4.1.5 on 2023-03-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_calendar_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
