# Generated by Django 4.1.5 on 2023-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_event_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='topic',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
