# Generated by Django 4.1.5 on 2023-02-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='action',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
