# Generated by Django 4.1.5 on 2023-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_calendar_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='person',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
