# Generated by Django 4.1.5 on 2023-03-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_months_studies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
    ]
