# Generated by Django 4.1.5 on 2023-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_event_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='place',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
