# Generated by Django 4.1.5 on 2023-03-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_calendar_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='congregation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
