# Generated by Django 4.1.5 on 2023-03-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_calendar_congregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
