# Generated by Django 4.1.5 on 2023-03-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_calendar_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555, null=True)),
            ],
        ),
    ]
