# Generated by Django 4.1.5 on 2023-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_placesstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesstand',
            name='congregation',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
