# Generated by Django 4.1.5 on 2023-03-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_placesstand_congregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='congregation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='icon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='place',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='topic',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='placesstand',
            name='congregation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placesstand',
            name='name',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
