# Generated by Django 4.1.5 on 2023-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_calendar_congregation_alter_calendar_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='at_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
