# Generated by Django 4.1.5 on 2023-03-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_calendar_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='arr_icon',
            field=models.JSONField(null=True),
        ),
    ]
